---
- name: Deploy VM on openshift openshift-virtualization
  hosts: localhost
  gather_facts: false

  vars:
    namespace: aac-poc
    labels:
      - app: aap-poc
    vm_name: ansible-deployed


  tasks:

    # - name: Authenticate to openshift cluster
    #   community.okd.openshift_auth:
    #     host: "{{ cluster_url }}"
    #     username: "{{ username }}"
    #     password: "{{ password }}"
    #     validate_certs: false
    #   register: openshift_auth_results
    #   delegate_to: localhost

    - name: Create Namespace
      kubernetes.core.k8s:
        # host: "{{ cluster_url }}"
        # api_key: "{{ openshift_auth_results.openshift_auth.api_key  }}"
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present
        validate_certs: false


    - name: Create an Openshift VM
      redhat.openshift_virtualization.kubevirt_vm:
        # host: "{{ cluster_url }}"
        # api_key: "{{ openshift_auth_results.openshift_auth.api_key  }}"
        validate_certs: false
        state: "{{ vm_state | default('present') }}"
        name: "{{ vm_name }}"
        namespace: "{{ namespace }}"
        labels:
          app: dadjoke
        instancetype:
          name: u1.medium
        preference:
          name: ansible-deployed
        spec:
          domain:
            devices:
              interfaces:
                - name: default
                  model: virtio
      delegate_to: localhost
