---
- name: Deploy VM on openshift openshift-virtualization
  hosts: localhost
  gather_facts: false

  vars:
    namespace: aac-poc
    labels:
      app: aap-poc
    vm_name: ansible-deployed


  tasks:
    - name: Create Namespace
      kubernetes.core.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present
        validate_certs: false


    - name: Create an Openshift VM
      redhat.openshift_virtualization.kubevirt_vm:
        validate_certs: false
        state: "{{ vm_state | default('present') }}"
        name: "{{ vm_name }}"
        namespace: "{{ namespace }}"
        labels:
          "{{ labels }}"
        instancetype:
          name: u1.medium
        preference:
          name: fedora
